#!/bin/bash
# Deployment Script for Physical AI & Humanoid Robotics Textbook

echo "==========================================="
echo "Physical AI & Humanoid Robotics Textbook Deployment"
echo "==========================================="

echo ""
echo "Step 1: Verifying backend is ready for Railway deployment..."
echo "- Backend is containerized with Dockerfile"
echo "- Procfile is configured for Railway"
echo "- Environment variables are documented in RAILWAY_DEPLOYMENT.md"

echo ""
echo "Step 2: Backend Deployment to Railway"
echo "--------------------------------------"
echo "To deploy the backend to Railway:"
echo "1. cd backend/"
echo "2. railway login"
echo "3. railway init"
echo "4. Add environment variables as documented in RAILWAY_DEPLOYMENT.md"
echo "5. railway up"

echo ""
echo "Step 3: Frontend Deployment to Netlify"
echo "---------------------------------------"
echo "After backend is deployed:"
echo "1. Update VITE_BACKEND_URL in .env with your Railway backend URL"
echo "2. Build the frontend: npm run build:netlify"
echo "3. Deploy to Netlify using the Netlify CLI or web interface"

echo ""
echo "Environment Variables Required:"
echo "==============================="
echo "Backend (set in Railway):"
echo "- FRONTEND_ORIGIN (your Netlify URL)"
echo "- DEPLOYED_FRONTEND_ORIGIN (your Netlify URL)"
echo "- QDRANT_URL"
echo "- QDRANT_API_KEY"
echo "- GROQ_API_KEY"
echo "- NEON_DATABASE_URL"
echo "- GITHUB_CLIENT_ID"
echo "- GITHUB_CLIENT_SECRET"

echo ""
echo "Frontend (set in .env before building):"
echo "- VITE_BACKEND_URL (your Railway backend URL)"

echo ""
echo "Required External Services:"
echo "==========================="
echo "1. Qdrant Cloud - Vector database for RAG"
echo "2. Neon PostgreSQL - Database for user accounts and chat history"
echo "3. Groq API - Fast inference for AI responses"
echo "4. GitHub OAuth App - Authentication provider"

echo ""
echo "Deployment Order:"
echo "================="
echo "1. Deploy backend to Railway first"
echo "2. Obtain backend URL"
echo "3. Update frontend .env with backend URL"
echo "4. Build and deploy frontend to Netlify"
echo "5. Test full functionality"

echo ""
echo "For detailed instructions, see:"
echo "- RAILWAY_DEPLOYMENT.md (for backend deployment)"
echo "- MEMORY_OPTIMIZATION.md (for frontend build optimization)"
echo "==========================================="