[build]
  command = "npm run build:netlify"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  NODE_OPTIONS = "--max-old-space-size=3072"
  NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[template.environment]
  NODE_VERSION = "20"